before_script:
  - mkdir build && cd build/

botan_cares_systemd_idn:
  script:
    - ../scripts/build_and_run_tests.sh -DWITH_BOTAN=1 -DWITH_CARES=1 -DWITH_SYSTEMD=1 -DWITH_LIBIDN=1

botan_cares_systemd:
  script:
    - ../scripts/build_and_run_tests.sh -DWITH_BOTAN=1 -DWITH_CARES=1 -DWITH_SYSTEMD=1 -DWITHOUT_LIBIDN=1

botan_cares_idn:
  script:
    - ../scripts/build_and_run_tests.sh -DWITH_BOTAN=1 -DWITH_CARES=1 -DWITHOUT_SYSTEMD=1 -DWITH_LIBIDN=1

botan_systemd_idn:
  script:
    - ../scripts/build_and_run_tests.sh -DWITH_BOTAN=1 -DWITHOUT_CARES=1 -DWITH_SYSTEMD=1 -DWITH_LIBIDN=1

cares_systemd_idn:
  script:
    - ../scripts/build_and_run_tests.sh -DWITHOUT_BOTAN=1 -DWITH_CARES=1 -DWITH_SYSTEMD=1 -DWITH_LIBIDN=1

cares_systemd:
  script:
    - ../scripts/build_and_run_tests.sh -DWITHOUT_BOTAN=1 -DWITH_CARES=1 -DWITH_SYSTEMD=1 -DWITHOUT_LIBIDN=1
