language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libidn2-0-dev libexpat1-dev uuid-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
